#!/bin/bash

USAGE="Usage: notify <title> <message>

example: notify 'test-refresh' 'Tests passed!'"


if [ -z "$1" ] || [ -z "$2" ]; then
    echo "$USAGE"
    exit 1
fi

title="$1"
message="$2"

if [ ! -z "$TMUX" ]; then
    tmux list-clients \
        | cut -f 1 -d : \
        | xargs -n1 -I{} tmux display-message -c {} "$message"
elif command -v noti >/dev/null 2>&1; then
    noti -t "$title" -m "$message"
elif command -v notify-send >/dev/null 2>&1; then
    notify-send "--app-name=$title" "$message"
fi


